version: "3.9"

services:
  snmp-simulator:
    image: tandrup/snmpsim
    container_name: go_auth_snmp_simulator
    restart: always
    ports:
      - "161:161/udp"
    volumes:
      - ./snmp/data:/usr/local/snmpsim/data
    environment:
      - SNMPSIM_ARGS=--data-dir=/usr/local/snmpsim/data --agent-udpv4-endpoint=0.0.0.0:161
    networks:
      - app-network

networks:
  app-network:
    driver: bridge