version: "3.9"

services:
  db:
    image: postgres:15
    container_name: go_auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: go_auth
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: go_auth_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: go_auth
      DB_PORT: 5432
      JWT_SECRET: mysecretkey
    volumes:
      - .:/app

volumes:
  db_data:
