version: "3.9"

services:
  db:
    image: postgres:15
    container_name: go_auth_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8056
      POSTGRES_DB: go_auth_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    container_name: go_auth_nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"  
    command: "--jetstream"

  snmp-simulator:
    image: tandrup/snmpsim
    container_name: go_auth_snmp_simulator
    restart: always
    ports:
      - "161:161/udp"
    volumes:
      - ./snmp/data:/usr/local/snmpsim/data
    environment:
      - SNMPSIM_ARGS=--data-dir=/usr/local/snmpsim/data --agent-udpv4-endpoint=0.0.0.0:161

  app:
    build: .
    container_name: go_auth_app
    restart: always
    depends_on:
      - db
      - nats
      - snmp-simulator
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 8056
      DB_NAME: go_auth_db
      DB_PORT: 5432
      JWT_SECRET: mysecretkey
      NATS_URL: nats://nats:4222
      NATS_RECONNECT: "true"

volumes:
  db_data: